# Generated by Django 5.1.4 on 2024-12-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completed_tasks',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_tasks',
        ),
    ]
