# Generated by Django 5.1.4 on 2024-12-24 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0002_initial'),
        ('project', '0003_remove_project_completed_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='completed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bug',
            name='total_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bug',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.project'),
        ),
    ]
